### ISSUE TITLE
No SVG assets?

### ISSUE THREAD

**Issue by JoshyPHP** [Ranks/emojione-assets#2]
The repository doesn't currently contain [any SVG files](https://github.com/Ranks/emojione-assets/search?utf8=%E2%9C%93&q=extension%3Asvg&type=), only PNGs. Are SVG assets going to be re-added as the repository is being set up or will EmojiOne 3.0 be limited to PNGs?

SVG images look much crisper than resized PNGs and it's not always possible to stick to the PNGs' native resolutions, so obviously losing that option would be detrimental.

**Comment by kevinranks** [comment]
Hey @JoshyPHP, 

I completely understand where you're coming from. The EmojiOne project has grown much larger than we initially anticipated and as a result our costs have skyrocketed. In order to keep the project alive we've decided to keep 128x128px pngs available for developers, which should cover most digital uses. 

For people that require larger artwork we've made available a number of licensing options.

The 2.x artwork is still available with SVGs, and you're welcome to keep using those.

**Comment by JoshyPHP** [comment]
The use case I had in mind was more about web pages than print or high resolution images. A 32px PNG scaled down to 24px or a 64px PNG scaled down to 40px looks blurry compared to an SVG image. It's also bigger in size, as SVG files will typically be smaller than their PNG counterpart.
